inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
  - 'spec/dummy/db/**/*'
  - 'vendor/**/*'
  DisplayCopNames: true
  NewCops: enable
  CacheRootDirectory: tmp # ie. tmp/rubocop_cache
  UseCache: true

Layout/EndAlignment:
  AutoCorrect: true

Layout/LineLength:
  Max: 120

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Max: 125

Metrics/BlockLength:
  CountComments: false  # count full line comments?
  IgnoredMethods:
    - 'context'
    - 'configure'
    - 'describe'
    - 'namespace'
    - 'shared_examples_for'
    - 'shared_examples'
    - 'pending'
    - 'shared_context'
    - 'xcontext'
    - 'xdescribe'
    - 'it'
  Exclude:
    - 'db/schema.rb'
    - 'spec/factories/**/*'
    - '*.gemspec'

Metrics/MethodLength:
  Max: 25

Metrics/ModuleLength:
  Exclude:
  - spec/**/*_spec.rb

Metrics/PerceivedComplexity:
  Enabled: false

Naming/PredicateName:
  Exclude:
  - spec/**/*.rb

Rails:
  Enabled: true

Rails/Date:
  EnforcedStyle: strict

Rails/FindBy:
  Enabled: true
  Include:
  - app/commands/**/*.rb
  - app/models/**/*.rb
  - app/view_models/**/*.rb

Style/CollectionMethods:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/SignalException:
  EnforcedStyle: semantic

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

