inherit_from: .rubocop_todo_0_49.yml

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
  - 'spec/dummy/db/**/*'
  - 'vendor/**/*'

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Max: 125

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 25

Metrics/ModuleLength:
  Exclude:
  - spec/**/*_spec.rb

Metrics/PerceivedComplexity:
  Enabled: false

Style/CollectionMethods:
  Enabled: true

Style/Documentation:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/PredicateName:
  Exclude:
  - spec/**/*.rb

Style/SignalException:
  EnforcedStyle: semantic

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInLiteral:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Rails:
  Enabled: true

Rails/Date:
  EnforcedStyle: strict

Rails/FindBy:
  Enabled: true
  Include:
  - app/commands/**/*.rb
  - app/models/**/*.rb
  - app/view_models/**/*.rb

Lint/EndAlignment:
  AutoCorrect: true
