#!/usr/bin/env bash

# quick hacky script that assumes you've got thredded checked out next to thredded-personalized-navigation
# and updates the relevant parts of this plugin that need it from thredded
# not 100% sure what the less hacky version might be (probably changes to thredded to include some of this in the gem
#
# at very least should make this a more structured file
# and then also add a notice to the top of the copied files that they have been copied from thredded

# update db from thredded
rm -fR ./spec/dummy/db/migrate
cp -pR ../thredded/db/migrate ./spec/dummy/db
cp -pR ../thredded/spec/dummy/db/migrate/* ./spec/dummy/db/migrate
rubocop -a ./spec/factories/thredded.rb
git add ./spec/dummy/db/migrate/*

# update factories from thredded
cp ../thredded/spec/factories.rb ./spec/factories/thredded.rb
rubocop -a ./spec/factories/thredded.rb
git add ./spec/factories/thredded.rb
# what about the rest of dummy? obviously we've added something to the initializer
